spring:
  #配置redis服务器
  redis:
    host: localhost
    port: 6379
    timeout: 3000
    #配置redis连接池
    jedis:
      pool:
        min-idle: 5
        max-wait: 2000
        max-active: 10
        max-idle: 5

